import { Suspense } from "react";
import Navbar from "./component/Navbar";
import SideBar from "./component/SideBar";
import ToastContainerProvider from "./component/ToastContainerProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import Loading from "./loading";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainerProvider />
        <Navbar />
        <div className="lg:grid lg:grid-cols-12">
          <SideBar />
          <Suspense fallback={<Loading />}>
            <main className="col-span-10 p-5">{children}</main>
          </Suspense>
        </div>
      </body>
    </html>
  );
}
